### ISSUE TITLE
제공할 서비스는 반응형이어야 하는가?

### ISSUE THREAD

**Issue by kwonjounghun** [jonghunkwon/walog#3]
우리가 만들어야할 블로그는 WEB과 모바일을 모두 하나의 소스로 제공하는 반응형이어야 할까요?

개인적인 의견
mobile과 PC는 운영 방식이 다르다고 생각합니다.
더 많은 정보를 제공할 수 있어서 다양한 엑션을 유도해볼 수 있는 PC와 다르게 한정된 정보를 통하여 원하는 성과에 집중해야하는 모바일의 기능 혹은 UX는 함께 쓰기 어려울 경우도 있을 것 같습니다.

pc와 mobile를 따로 운영하면 어떨까요?

**Comment by seungahhong** [comment]
블로그마다 차이는 있을꺼 같은데요.. 복잡하지 않은 UI, 변경이 거의 없는 UI라면 굳이 나누지 않고 하나의 소스에서 제공하는게 관리에 용이할 것 같습니다.

**Comment by kwonjounghun** [comment]
논의 결과
- 반응형으로 작업을 진행
- 추후에 필요에 의해서 모바일과 PC를 나누어 관리하도록 한다.
