### ISSUE TITLE
공통 CSS 정의

### ISSUE THREAD

**Issue by da1464** [jonghunkwon/walog#4]
기술 블로그에 공통으로 정의가 필요할 만한 사항들입니다.
추가나 개선이 필요한 부분들 논의해 보면 좋을 것 같습니다 🤔

<hr>

### reset.css
<details><summary>reset.css</summary>

<pre>
scss로 변환해서 사용.

/* 모든 요소에 대한 테두리 상자 크기 조정 */
*,
*::before,
*::after { box-sizing:border-box; } 

/* 모든 브라우저에서 제공하는 여백을 제거, 보더 0으로 셋팅 - 요건 필요한 태그만  */
body, button, dd, dl, dt, fieldset, form, 
h1, h2, h3, h4, h5, h6, input, legend, li, ol, 
p, select, table, td, textarea, th, ul {
  margin: 0;
  padding: 0;
  border: 0;
} 

/* 기본적으로 브라우저에서 제공하는 리스트 스타일 제거 */
ul,ol,li {
  list-style: none; 
}

/* 필요할 경우 사용 */
blockquote, q {
	quotes: none;
}

blockquote:before, blockquote:after,
q:before, q:after {
	content: '';
	content: none;
}

/* 컨테이너를 초과할 수 없도록 설정 */
img, picture, video, canvas, svg {
  max-width: 100%; 
}

* 모든 브라우저에서 아래 요소의 정렬을 변경 */ 
audio,
canvas,
img,
svg,
input,
select,
textarea,
button {
  vertical-align: middle;
}

iframe,
img,
video {
  vertical-align: top;
}

/* 브라우저 너비에 맞춰 확장 */
video, img {
  max-width: 100%;
  height: auto;
}

/* 브라우저 기본으로 제공하는 이탤릭체 제거 */
address,cite,dfn,em,var {
  font-style: normal;
  font-weight: 400;
}

a,
button {
  outline: none;
  -webkit-appearance: none;
}

a {
  color: inherit;
  /* 부모 객체의 color값을 상속받게 함 */
  text-decoration: none;
}

/* 기본적으로 브라우저에서 제공하는 스타일 제거 */
button {
  background-color: none; 
  color: inherit;
}

/* disable이 아닐 경우 cursor를 pointer로 지정 */
button:not(:disabled), input:not(:disabled), input:not(:disabled) + label {
  cursor: pointer;
}

/* placeholder color 값 부모 객체의 color값을 상속받게 함 */
input::-webkit-input-placeholder {
  color: inherit;
}

input[type=text]::-ms-clear,
input[type=search]::-webkit-search-cancel-button, 
input[type=search]::-webkit-search-decoration {
  display: none; /* ie10 이상에서 input textbox에 포커스시 생기는 삭제(x) 버튼 숨기기 */
}

table { /* 표에는 추가 테두리 간격이 포함하지 않음 */
  border-collapse: collapse;
  border-spacing: 0;
}

/* 
font-smoothing 속성은 비표준이긴 하나, 
하위 픽셀이 아닌 픽셀 수준에서 글꼴을 부드럽게 합니다. 
어두운 배경의 밝은 텍스트에 대해 서브픽셀 렌더링에서 앤티앨리어싱으로 전환하면 더 밝게 보입니다.
참고로, wadiz-frontend에 들어가 있음*/
body {
  font-family: Roboto, 'Noto Sans KR', dotum,sans-serif;
  font-weight: 400; /* @font-face에서 디폴트로 사용할 font-weight 값으로 사용 */
  line-height: 1.2 /* inherit ? */;
  -webkit-tap-highlight-color: transparent; /* 모바일에서 링크의 회색 강조 표시를 제거 */
  -webkit-text-size-adjust: none; /* text크기를 자동으로 조절하지 않을 경우 사용 */
  -webkit-font-smoothing: antialiased; /* 폰트를 부드럽게 */ 
}
</pre></details>

<br>

### 폰트, 컬러
와플에 정의 된 와디즈 공통 사용하고, 기술 블로그에 적용될 사이즈를 정의하면 좋을 것 같습니다.
[FONT](https://git.wadizcorp.com/projects/FE/repos/wadiz-waffle/raw/packages/waffle/src/styles/common/_font.scss?at=refs%2Fheads%2Fmaster) / [COLOR](https://git.wadizcorp.com/projects/FE/repos/wadiz-waffle/raw/packages/waffle/src/styles/common/_color.scss?at=refs%2Fheads%2Fmaster)

<br>

### mixin도 정의하면 좋을까요?
<details><summary>mixin 예시</summary>
<pre>
/* float 해제 */
@mixin clear {
    &::after {
      content: ""; 
      clear: both;
      display: block;
    }
}

/* 말줄임, 다중 말줄임 */
@mixin ellipsis($lines:null, $max-height: null) {
  @if($lines==null){
    overflow: hidden;
    display: block;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  @else{
    overflow: hidden;
    display: block;
    display: -webkit-box;
    max-height: $max-height;
    text-overflow: ellipsis;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: $lines;
    }
}
</pre></details>

<br>

#### 반응형으로 간다면 breakpoint도 와디즈 공통을 따르면 좋을까요?
- 분기가 많지는 않을 것 같고 768 기준으로만 나눠도 크게 이슈는 없을 것 같다는 생각도 드네요~?

**Comment by seungahhong** [comment]
emotion을 사용한다면.. props를 통해서 컴포넌트 분리도 가능한지라 제 생각엔 mixin 꼭 지원 안해도 되지 않을까 싶네요..
혹시 기존 scss를 가져와야한다면?? 요런거 설치해서 하면 되는거 같습니다.

https://www.npmjs.com/package/emotion-mixins

**Comment by kwonjounghun** [comment]
font와 color는 와플에 있는걸 쓰지만 어떤경우에 써야할지는 논의(요구사항 정리)가 필요.

mixin은 다슬프로님이 학습 후 다시 논의 하겠다.

**Comment by da1464** [comment]
${emotionReset} 제거
font는 LIght는 불필요할 것 같아 제거. (필요 시 추가)
ttf(true type font)는 IE 지원 x -> IE도 동일하게 표현해야하는지?
