### ISSUE TITLE
server 블로그 API 추가

### ISSUE THREAD

**Issue by seungahhong** [jonghunkwon/walog#7]
# walog 블로그 메인화면 API 명세
type |   |   |   |  
-- | -- | -- | -- | --
meta | title |   |   |  
  | description |   |   |  
  | og | title |   |  
  |   | description |   |  
  |   | image |   |  
array | postItems |   |   |  
  |   | id |   |  
  |   | title |   |  
  |   | description |   |  
  |   | image |   |  
  |   | category |   |  
  |   | tags |   |  
  |   | excerpt |   | 간단 설명
string[] | tagItems |   |   |  
string[] | categoryItems |   |   | 필터(FE, BE)
  |   |   |   |  

# walog 블로그 상세페이지 API 명세
type |   |   |   |   |  
-- | -- | -- | -- | -- | --
string | title |   |   |   | 타이틀
string | description |   |   |   | 설명
string | author |   |   |   | 작성자
date | date |   |   |   | 작성일자
string | content |   |   |   | html 컨텐츠
string | category |   |   |   | 속해있는 카테고리(FE)
array | tags |   |   |   | 태그 배열
object | og |   |   |   |  
string |   | title |   |   |  
string |   | description  |   |   |  
string |   | image |   |   |  
object | twitter |   |   |   |  
string |   | title |   |   |  
string |   | description |   |   |  
string |   | image |   |   |  
string | social | github |   |   | url
string |   | facebook |   |   | url
string |   | twitter |   |   | url
string | prev | id |   |   | 이전 링크
string |   | title |   |   |  
string | next | id |   |   | 다음 링크
string |   | title |   |   |

**Comment by seungahhong** [comment]
프로님들.. 우아한형제들 기술블로그 보면서 제가 생각한 API 명세들 입니다.
확인해보시고 추가/삭제/수정 다 가능하니 확인부탁드려요^^

**Comment by kwonjounghun** [comment]
@seungahhong 저는 좋은거 같습니다!

**Comment by DinnerKang** [comment]
meta라는 Object로 title, description, og 를 넣는건 어떠신가요 !
postItems도 postList or posts가 좋을 것 같은데 (이건 취향 ㅎㅎ)

**Comment by DinnerKang** [comment]
og -> openGraph 어떠십니까..! (인터페이스 만들다가 og라고 하니깐 이상해서... 은주프로님 닮아가나)

**Comment by DinnerKang** [comment]
walog 블로그 메인화면 API 명세 에서 질문이 있습니다.

여기 API에 meta가 들어가는데, 홈의 메타태그를 동적으로 바꾸고 싶으셔서 넣으신거죠 ??

그렇다면 api분리를 해야 어울린다고 생각되는데 어떻게 생각하시나요 ~!??
post와 다른 성격의 데이터 같아서요 !!

**Comment by seungahhong** [comment]
> walog 블로그 메인화면 API 명세 에서 질문이 있습니다.
> 
> 여기 API에 meta가 들어가는데, 홈의 메타태그를 동적으로 바꾸고 싶으셔서 넣으신거죠 ??
> 
> 그렇다면 api분리를 해야 어울린다고 생각되는데 어떻게 생각하시나요 ~!?? post와 다른 성격의 데이터 같아서요 !!

@DinnerKang 프로님, 메타태그에 대한 설계??스펙??이 정해지지 않아서 동적으로 변경이 가능하게 처리한 로직이랍니다.
프로님이 고민하셨을때 분리해야한다고 생각하시면 분리해주시면 될 것 같습니다.

**Comment by seungahhong** [comment]
> og -> openGraph 어떠십니까..! (인터페이스 만들다가 og라고 하니깐 이상해서... 은주프로님 닮아가나)

@DinnerKang 프로님, 저도 요건 동의합니다.
단, 요렇게 한데는 의미는 있었어요~~

1. 네트워크 비용을 줄일 수 있는 부분이라면 최대한 줄여본다.
2. 개발자가 판단했을때 줄임 단어를 보고 의미를 알 수 있는 속성명을 사용한다.

-> 요런 생각으로 og라고 했답니다.

**Comment by seungahhong** [comment]
> Object

**Comment by seungahhong** [comment]
> meta라는 Object에 title, description, og 를 넣는건 어떠신가요 ! postItems도 postList or posts가 좋을 것 같은데 (이건 취향 ㅎㅎ)

@DinnerKang 프로님, 요건 좋은데요.. 명확하네요.. twitter만 따르게 가는 경우는 없겠죠?? 그렇다면 프로님 의견대로 변경하는게 맞는거 같네요
